### ISSUE TITLE
Doc improvements, enabling newcomers to run and inspect the behavior of the extension

### ISSUE THREAD

**Issue by motin** [benmiroglio/embedded-webextension-example#1]
* Remove of all repo-contained documentation that is irrelevant to running this popup-enhanced hello world example
* Add to the root README file: instructions starting from git clone -> installing deps -> building the xpi -> running the extension -> triggering the extension (including resetting any stored data the prevents the shield study to initiate) -> seeing telemetry pings etc logged
* Include information about global requirements (for instance, I noticed that mustache was required to build the xpi)
* Rename this extension to something like "shield-study-embedded-webextension-hello-world-example" to separate it from the other 4-8 example repos :)

**Comment by benmiroglio** [comment]
Please find the updated readme with all the necessary details to get you started. Feel free to reach out / file more issues if you run into any problems! :)

**Comment by motin** [comment]
Thanks a bunch for quick action on this issue! :)
